<?php
if ( ! defined( 'ABSPATH' ) ) exit;
class SDW_Delivery {
    public static function is_motorcycle_method($label,$method_id=''){ $o=SDW_Core::options(); $keywords=array_filter(array_map('trim',explode(',',(string)$o['motorcycle_keywords']))); $raw=$label.' '.$method_id; $haystack=function_exists('mb_strtolower')?mb_strtolower($raw):strtolower($raw); foreach($keywords as $keyword){$needle=function_exists('mb_strtolower')?mb_strtolower($keyword):strtolower($keyword); if(''!==$needle&&false!==strpos($haystack,$needle))return true;} return false; }
    public static function available_dates($is_motorcycle=false){ $o=SDW_Core::options(); $tz=wp_timezone(); $now=new DateTimeImmutable('now',$tz); $delay=max(0,min(30,(int)$o['delay_days'])); if(!empty($o['cutoff_time'])){$cutoff=DateTimeImmutable::createFromFormat('Y-m-d H:i',$now->format('Y-m-d').' '.$o['cutoff_time'],$tz);if($cutoff&&$now>$cutoff)$delay++;} $cursor=$now->setTime(0,0)->modify('+'.($delay+1).' day'); $dates=array();$max=max(1,min(60,(int)$o['max_days']));$guard=0; while(count($dates)<$max&&$guard<300){if(self::is_open_day($cursor,$is_motorcycle))$dates[]=$cursor;$cursor=$cursor->modify('+1 day');$guard++;} return $dates; }
    public static function is_open_day(DateTimeImmutable $date,$is_motorcycle=false){ $o=SDW_Core::options(); if($is_motorcycle&&'yes'===$o['motorcycle_all_days']) return true; if(in_array($date->format('w'),(array)$o['weekend_days'],true))return false; if('yes'===$o['iran_holidays']&&SDW_Iran_Calendar::is_holiday($date))return false; $lines=preg_split('/\r\n|\r|\n/',(string)$o['holidays']); foreach(array_filter(array_map('trim',$lines)) as $line){$normalized=SDW_Calendar::normalize_holiday($line,$o['calendar']);if($normalized&&$normalized===$date->format('Y-m-d'))return false;} return true; }
    public static function weekday($w,$lang=null){$lang=$lang?:SDW_Core::language();$fa=array(0=>'یکشنبه',1=>'دوشنبه',2=>'سه‌شنبه',3=>'چهارشنبه',4=>'پنجشنبه',5=>'جمعه',6=>'شنبه');$en=array(0=>'Sunday',1=>'Monday',2=>'Tuesday',3=>'Wednesday',4=>'Thursday',5=>'Friday',6=>'Saturday');$map='fa'===$lang?$fa:$en;return isset($map[$w])?$map[$w]:'';}
    public static function formatted_date(DateTimeImmutable $date){$o=SDW_Core::options();return SDW_Calendar::format($date,$o['calendar'],SDW_Core::language());}
    public static function occasion(DateTimeImmutable $date){$o=SDW_Core::options(); if('yes'!==$o['iran_occasions'])return '';return SDW_Iran_Calendar::label($date,SDW_Core::language());}
    public static function format_stored_date($iso){try{$d=new DateTimeImmutable($iso,wp_timezone());return self::weekday((int)$d->format('w')).' - '.self::formatted_date($d);}catch(Exception $e){return $iso;}}
}
